### ISSUE TITLE
iTunes-bridge not detecting song

### ISSUE THREAD

**Issue by ManagerCat** [AngryKiller/iTunes-bridge#10]
I'm using Apple Music on my Macbook. I'm trying to detect the song that it's playing. I'm using the example code from the README.md. Even when I'm playing a song, it will log: "iTunes is not playing at the moment.
iTunes is not longer playing!" The emitter also doesn't seem to work.

**Comment by AngryKiller** [comment]
Hi, are you on macOS Big Sur? I didn't test it on that version so it might be the problem

**Comment by ManagerCat** [comment]
I am on Catalina, thanks for the quick reply!

**Comment by ManagerCat** [comment]
It seems like the path might be incorrect. The music library is under /Users/steve/Music/Music/Music Library.musiclibrary

**Comment by AngryKiller** [comment]
You're right about that, but the musiclibrary file is only used for certain functions and iTunes-bridge should work even without it. It currently investigating that issue

**Comment by AngryKiller** [comment]
I just pushed a fix that should resolve issues with Catalina and later, I'm just setting up a Mojave VM to test if I didn't broke things for previous versions before pushing on npm.

**Comment by AngryKiller** [comment]
It now works with both iTunes and Music app, so this is fixed.
