### ISSUE TITLE
M1 Mac Support

### ISSUE THREAD

**Issue by EazyFTW** [AngryKiller/iTunes-bridge#16]
I recently got an M1 MacBook Pro and this seems to not work with Arm64 for some reason?

<img width="257" alt="image" src="https://user-images.githubusercontent.com/13033307/176591823-ddb95ab0-d0f6-481c-bdb3-a66486d670c7.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/13033307/176591843-5d0625c6-2cac-4095-8555-898f2de2d78b.png">

Getting the track info does not work but detecting that iTunes (Music) is open, does in-fact work. No idea why this might be. Events also do not work, probably due to it not detecting the current track correctly.

If you need help implementing a fix or someone to test a fix, let me know.

**Comment by EazyFTW** [comment]
I had to re-install WebStorm due to some issues I was having and this time it asked me for permissions to access the Music app, it didn't make much sense that this would be an issue only on an M1 Mac, and it looks like it isn't. Clicking "Ok" has fixed the issue!

![image](https://user-images.githubusercontent.com/13033307/176962038-1925c699-cfa9-429b-a52b-2d1b66b9424f.png)

**Comment by AngryKiller** [comment]
> I had to re-install WebStorm due to some issues I was having and this time it asked me for permissions to access the Music app, it didn't make much sense that this would be an issue only on an M1 Mac, and it looks like it isn't. Clicking "Ok" has fixed the issue!
> 
> ![image](https://user-images.githubusercontent.com/13033307/176962038-1925c699-cfa9-429b-a52b-2d1b66b9424f.png)

You need to allow it to control Music, it uses macOS Automation scripts, and if you are running it in CLI it will ask you to authorize the app in which your CLI is running, in this case WebStorm. In theory the pop-up should always show when needed, but this is macOS handling it and I don't think we can have control over it. It may be possible to catch the error however and display an adequate error message relating to the Privacy settings of macOS
